replace offense_type = "any" if offense_type == "All offenses"
replace offense_type = "violent" if offense_type == "Violent offenses"
replace offense_type = "murder" if offense_type == "Murder"
replace offense_type = "rape" if offense_type == "Rape"
replace offense_type = "robbery" if offense_type == "Robbery"
replace offense_type = "assault" if offense_type == "Assault"
replace offense_type = "other violent" if offense_type == "Other violent"
replace offense_type = "property" if offense_type == "Property offenses"
replace offense_type = "burglary" if offense_type == "Burglary"
replace offense_type = "larceny/theft" if offense_type == "Theft"
replace offense_type = "motor vehicle theft" if offense_type == "Motor vehicle theft"
replace offense_type = "forgery/fraud" if offense_type == "Forgery"
replace offense_type = "forgery/fraud" if offense_type == "Fraud"
replace offense_type = "other property" if offense_type == "Other property"
replace offense_type = "drug" if offense_type == "Drug offenses"
replace offense_type = "drug trafficking" if offense_type == "Trafficking"
replace offense_type = "other drug" if offense_type == "Other drug"
replace offense_type = "public order" if offense_type == "Public-order offenses"
replace offense_type = "weapons" if offense_type == "Weapons"
replace offense_type = "driving related" if offense_type == "Driving-related"
replace offense_type = "other public order" if offense_type == "Other public-order"
